### ISSUE TITLE
Upgrade Steamtools to Steamworks

### ISSUE THREAD

**Issue by DJPlaya** [TF2-Sandbox-Studio/TF2SB#11]
`Unable to load plugin "TF2Sandbox-Core.smx": Required extension "SteamTools" file("steamtools.ext") not running`
Basicly Yea, SteamTools is broken since a loong Time now.
A Workaround to Plugins still not using Steamworks is [>this<](https://github.com/KyleSanderson/SteamWorks/blob/master/Pawn/swag.sp), still you should at least unrequire this Extension

**Comment by BattlefieldDuck** [comment]
SteamTools work fine in my server.

**Comment by DJPlaya** [comment]
Shall I Update the Code and create a pull Request for you?

**Comment by Danct12** [comment]
Since this is open-source, feel free to do whatever you want to it.

**Comment by Danct12** [comment]
Alright, I have removed the SteamTools references in the code, I'll push it up when I'm back home.

**Comment by Danct12** [comment]
Pushed in commit [9d3707a](https://github.com/Danct12/TF2SB/commit/9d3707aca2b16c625f5baaa9f4a722f8a5914592)
